// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Security.Cryptography;
using System.Text;

namespace SIP.Common
{
	public class DEncrypt
	{
		public DEncrypt ()
		{
		}

		#region MD5 Encrypt
		/// <summary>
		/// Make 128 bit MD5 string
		/// </summary>
		/// <param name="text">要加密的字符串</param>    
		public static string MakeMD5(string text)
		{
			
			//Check if string text is null
			if (Utilities.IsNullOrEmpty<string>(text))
			{
				return "";
			}
			
			byte[] inputByte;
			inputByte = System.Text.Encoding.ASCII.GetBytes(text);
			
			return MakeMD5(inputByte);
		}
		
		/// <summary>
		/// 128位MD5算法加密Byte数组
		/// </summary>
		/// <param name="data">要加密的Byte数组</param>    
		public static string MakeMD5(byte[] data)
		{
			//Check if the data is null
			if (Utilities.IsNullOrEmpty<byte[]>(data))
			{
				return "";
			}
			
			try
			{
				//创建MD5密码服务提供程序
				MD5CryptoServiceProvider md5 = new MD5CryptoServiceProvider();
				
				//计算传入的字节数组的哈希值
				byte[] result = md5.ComputeHash(data);
				
				//释放资源
				md5.Clear();
				
				//返回MD5值的字符串表示
				return Convert.ToBase64String(result);
			}
			catch
			{
				
				//LogHelper.WriteTraceLog(TraceLogLevel.Error, ex.Message);
				return "";
			}
		}
		#endregion
	}
}

