// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace SIP.Common
{
	public static class Utilities
	{
		#region Check if the object is null
		/// <summary>
		/// return true if the object is null.
		/// </summary>
		/// <typeparam name="T">Data type</typeparam>
		/// <param name="data">Data</param>        
		public static bool IsNullOrEmpty<T>(T data)
		{
			//If null
			if (data == null)
			{
				return true;
			}
			
			//If there is nothing
			if (data.GetType() == typeof(String))
			{
				if (string.IsNullOrEmpty(data.ToString().Trim()))
				{
					return true;
				}
			}
			
			//If DBNull
			if (data.GetType() == typeof(DBNull))
			{
				return true;
			}
			
			//Not null
			return false;
		}
		
		/// <summary>
		/// return true if the object is null.
		/// </summary>
		/// <param name="data">Data Object</param>
		public static bool IsNullOrEmpty(object data)
		{
			//If null
			if (data == null)
			{
				return true;
			}
			
			//If there is nothing
			if (data.GetType() == typeof(String))
			{
				if (string.IsNullOrEmpty(data.ToString().Trim()))
				{
					return true;
				}
			}
			
			//If DBNull
			if (data.GetType() == typeof(DBNull))
			{
				return true;
			}
			
			//Not null
			return false;
		}
		#endregion
	}
}

