// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace SIP.FastVRTools.Cameras
{
	[Serializable]
	public class CharacterDriverMovingPlatform
	{
		public bool m_enable = true;

		public MovementTransferOnJump m_movementTransfer = MovementTransferOnJump.PermaTransfer;

		public Transform m_hitPlatform;

		public Transform m_activePlatform;

		public Vector3 m_activeLocalPoint;

		public Vector3 m_activeGlobalPoint;

		public Quaternion m_activeLocalRotation;

		public Quaternion m_activeGlobalRotation;

		public Matrix4x4 m_lastMatrix;

		public Vector3 m_platformVelocity;

		public bool m_newPlatform;

		public CharacterDriverMovingPlatform ()
		{
		}
	}
}

