// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace SIP.FastVRTools.Cameras
{
	public class CharacterDriverSliding
	{
		public bool m_enable;
		
		public float m_slidingSpeed = 15.0f;
		
		public float m_sidewayControl = 1.0f;
		
		public float m_speedControl = 0.4f;

		public CharacterDriverSliding ()
		{
		}
	}
}

